### ISSUE TITLE
Incorrect record value parsing by GetRecords for records with a type in private-use range 

### ISSUE THREAD

**Issue by mjl-** [libdns/rfc2136#6]
The value of such records contains the full resource record instead of only the value. The problem is here:

https://github.com/libdns/rfc2136/blob/ec2c145c438db71ca70120dca42f275c0ccbf2e2/conversion.go#L25

It tries to get the record value by formatting the full RR, and the header of the RR, and removing the header string from the full string. This does not work for private-use types. The full record string does not start with the header string for private-use type records, so nothing is stripped and the full record makes it into the libdns.Record.Value field.

Package github.com/miekg/dns parses private use records as unknown/generic https://pkg.go.dev/github.com/miekg/dns#RFC3597 records, which marshals (the header of a) full record differently than a header would on its own because of using "CLASS1" instead of "IN" for the class, see https://github.com/miekg/dns/blob/v1.1.62/types.go#L1231. The header starts with "<name> <ttl> IN TYPE... ". The full RFC3597 record with class INET starts with "<name> <ttl> CLASS1 TYPE...".

As a fix, I would suggest testing for parsed RRs to be RFC3597, and explicitly formatting its header to match what package dns returns for the full record, then trimming that.

For context, BIND adds a private-use record with type 65534 to zones when (automatic) DNSSEC is enabled. https://bind9.readthedocs.io/en/v9.18.13/chapter5.html#monitoring-with-private-type-records.

It seems the "dnsupdate" provider has the same issue, https://github.com/libdns/dnsupdate/blob/2e79c50ea2ee12b484ae312b13e4ac81ffe78623/provider.go#L179.

**Comment by KoHcoJlb** [comment]
I've created this provider primarily for use with Caddy, which does not use these records. However, if you have a use case for them, fell free to submit a PR.

**Comment by mjl-** [comment]
Thanks, created a PR just now.
I'm transforming these libdns.Record's to dns.RR's again, and back to libdns.Record later on, so I need them to be well-formed.

**Comment by mjl-** [comment]
Awesome, thanks for the quick response and tagged version!
